"""Added is_admin field to User model

Revision ID: 4952bd93c48d
Revises: fca0f829d9d1
Create Date: 2025-01-29 12:16:48.595675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4952bd93c48d'
down_revision = 'fca0f829d9d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###
