"""Updated User model - removed is_admin, added timestamps

Revision ID: 5c5d97d02e0a
Revises: 4952bd93c48d
Create Date: 2025-01-29 12:26:42.427633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c5d97d02e0a'
down_revision = '4952bd93c48d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('is_approved',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.BOOLEAN(), nullable=True))
        batch_op.alter_column('is_approved',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###
