"""Initial migration.

Revision ID: 9702b065ba4a
Revises: 34b7a3490822
Create Date: 2025-01-31 15:56:30.262106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9702b065ba4a'
down_revision = '34b7a3490822'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        pass  # Placeholder to prevent indentation error
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('instructor_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_course_instructor', 'user', ['instructor_id'], ['id'])
    # ### end Alembic commands ###
